### ISSUE TITLE
Lombok var incompatible with Java 11+

### ISSUE THREAD

**Issue by williewheeler** [ExpediaGroup/adaptive-alerting#561]
It seems that Lombok's var doesn't work with Java 11+:

https://stackoverflow.com/questions/53866929/unable-to-use-lombok-with-java-11

I'm running into issues trying to compile against a Java 12 SDK:

```
Caused by: org.apache.maven.reporting.MavenReportException:
Exit code: 1 - /Users/willie/git/adaptive-alerting/anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/DetectorManager.java:28: error: illegal reference to restricted type 'var'
import lombok.var;
```

Upgrade the Lombok dependency.

**Comment by jcushing-cfa** [comment]
Java 10 added the `var` keyword, so you can simply use `var` without the import.

**Comment by conradbekondo** [comment]
@jcushing-cfa Does it work as well with JDK 17? I've tried it with JDK 17, but it's not working
